### ISSUE TITLE
Rated power draw?

### ISSUE THREAD

**Issue by CCS86** [Ultimaker/HeatedBedUpgrade#1]
Hi guys, I have searched everywhere for the rated power consumption of this bed kit. I am trying to calculate my totals and that data would be great!

**Comment by Ghostkeeper** [comment]
I asked around. The upgrade kit uses the same heated bed as the Ultimaker 2 so its power draw will be the same. Except that there is a new power supply included that works on 19V instead of 12V, and a transformer that converts the 19V into 12V for the UMO's PCB.

**Comment by Ghostkeeper** [comment]
I was told by @cdeboer that the bed takes in 7 amperes when it's heating from 20 degrees. This is the maximum power draw it's tested for. As the bed approaches its target temperature this power draw is reduced.

I guess if you're looking to calculate how much energy your printers use, it's best to install a measuring device in the power socket or something. This will also account for the age of this equipment.

**Comment by CCS86** [comment]
Thanks ghostkeeper, this was for the purpose of sizing a new power supply when upgrading my printer's electronics.

It was my understanding that in the UMO kit runs on 24v, and the daughterboard steps that down to 19v for the controller.

Measuring the resistance at room temp, of the bed heater, to use V^2/R, and get roughly 175w.

How does that compare to the UM2's rating?

**Comment by Ghostkeeper** [comment]
Don't take the "12V" thing from me. I may be misremembering this. It's been years, sorry! The information I got from cdeboer though is factual as he looked it up.

I'm really not the best person to answer this. I'm trying to answer though because likely nobody who is reading this is qualified to answer your question. It's mostly just software engineers that use Github. Maybe it's better to take this up with the real support chain?
